### ISSUE TITLE
wsrec does not have a release version

### ISSUE THREAD

**Issue by sparvu** [kronometrix/recording#117]
wsrec does not honour the release version. 

```
krmx@raspberrypi:~/workspace/kronometrix/recording/bin $ ./wsrec -V
Unknown option: V
USAGE: wsrec [-dp] | [interval [count]]
   eg, wsrec         # print human readable output
       wsrec 5       # print every 5 seconds
       wsrec 1 5     # print 5 times, every 1 second
       wsrec -p 60   # print every 60 seconds parseable output

 FIELDS:
   #01 timestamp  : seconds since Epoch, time
   #02 ih         : indoor humidity, number
   #03 oh         : outdoor humidity,, number
   #04 ita        : indoor air temperature Celsius, number
   #05 ota        : outdoor air temperature Celsius, number
   #06 dpa        : outdoor dew point air temperature Celsius , number
   #07 wca        : outdoor wind chill temperature, Celsius, number
   #08 wind       : wind speed m/s, rate
   #09 wgust      : wind gust m/s, rate
   #10 windir     : wind Direction
   #11 rain1      : rain 1 hours, number
   #12 rain24     : rain 24 hours, number
   #13 totalrain  : total rain, number
   #14 pres       : absolute air pressure, number

 NOTES: Retrieves and logs the weather stats from the following weather 
        stations: WH-1080/1081
```
